2024-11-26 20:34:50,594 ERROR: Exception on /prompts [GET] [in /Users/calsmith/CascadeProjects/AudioMaster/venv/lib/python3.11/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/calsmith/CascadeProjects/AudioMaster/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/calsmith/CascadeProjects/AudioMaster/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/calsmith/CascadeProjects/AudioMaster/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/calsmith/CascadeProjects/AudioMaster/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/calsmith/CascadeProjects/AudioMaster/venv/lib/python3.11/site-packages/flask_login/utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/calsmith/CascadeProjects/AudioMaster/venv/lib/python3.11/site-packages/flask_login/login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/calsmith/CascadeProjects/AudioMaster/venv/lib/python3.11/site-packages/flask_login/utils.py", line 120, in login_url
    base = expand_login_view(login_view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/calsmith/CascadeProjects/AudioMaster/venv/lib/python3.11/site-packages/flask_login/utils.py", line 97, in expand_login_view
    return url_for(login_view)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/calsmith/CascadeProjects/AudioMaster/venv/lib/python3.11/site-packages/flask/helpers.py", line 232, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/calsmith/CascadeProjects/AudioMaster/venv/lib/python3.11/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/calsmith/CascadeProjects/AudioMaster/venv/lib/python3.11/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/calsmith/CascadeProjects/AudioMaster/venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'auth.login'. Did you mean 'outlines.view_outline' instead?
2024-11-26 20:36:12,551 INFO: AudioV4 startup [in /Users/calsmith/CascadeProjects/AudioMaster/app.py:48]
2024-11-27 13:31:02,157 INFO: AudioV4 startup [in /Users/calsmith/CascadeProjects/AudioMaster/app.py:48]
2024-11-27 13:32:24,812 ERROR: Error getting routes: 'MapAdapter' object has no attribute 'iter_rules' [in /Users/calsmith/CascadeProjects/AudioMaster/routes/docs.py:37]
2024-11-27 13:33:38,114 ERROR: Error getting routes: 'MapAdapter' object has no attribute 'iter_rules' [in /Users/calsmith/CascadeProjects/AudioMaster/routes/docs.py:37]
2024-11-27 13:39:57,452 ERROR: Error getting routes: 'MapAdapter' object has no attribute 'iter_rules' [in /Users/calsmith/CascadeProjects/AudioMaster/routes/docs.py:37]
2024-11-27 13:42:05,692 ERROR: Error getting routes: 'MapAdapter' object has no attribute 'iter_rules' [in /Users/calsmith/CascadeProjects/AudioMaster/routes/docs.py:37]
2024-11-27 13:43:47,807 ERROR: Error getting routes: 'MapAdapter' object has no attribute 'iter_rules' [in /Users/calsmith/CascadeProjects/AudioMaster/routes/docs.py:37]
2024-11-27 13:44:50,855 ERROR: Error getting routes: 'MapAdapter' object has no attribute 'iter_rules' [in /Users/calsmith/CascadeProjects/AudioMaster/routes/docs.py:37]
2024-11-27 13:45:52,636 ERROR: Error getting routes: 'MapAdapter' object has no attribute 'iter_rules' [in /Users/calsmith/CascadeProjects/AudioMaster/routes/docs.py:37]
